services: 
  app:
    build: .
    environment:
      SGFTE_DB_URL: ${SGFTE_DB_URL}
      SGFTE_DB_USER: ${SGFTE_DB_USER}
      SGFTE_DB_PASSWORD: ${SGFTE_DB_PASSWORD}
      SGFTE_MAIL_HOST: ${SGFTE_MAIL_HOST}
      SGFTE_MAIL_PORT: ${SGFTE_MAIL_PORT}
      SGFTE_MAIL_SSL: ${SGFTE_MAIL_SSL}
      SGFTE_MAIL_USER: ${SGFTE_MAIL_USER}
      SGFTE_MAIL_PASSWORD: ${SGFTE_MAIL_PASSWORD}
      SGFTE_APP_BASE_URL: ${SGFTE_APP_BASE_URL}
      SGFTE_BANK_SECRET: ${SGFTE_BANK_SECRET}
    ports:
      - "8080:8080"
