-- ============================================================
-- SGFTE · Esquema completo (Oracle)
-- Sistema de Gestión de Fondos, Tarjetas y Empleados
-- ------------------------------------------------------------
-- Ejecutar conectado al esquema de la app (usuario SGFTE en FREEPDB1).
-- Convención: identificadores en inglés. Moneda única: MXN.
-- Jerarquía: cardholder 1─N account 1─N card. Concentradora = fuente de fondos.
--
-- Este archivo es el esquema CANÓNICO: crea la base desde cero, ya con todo lo
-- que fueron añadiendo las migraciones. Si ya tienes una base creada, NO uses
-- este archivo: aplica las V en orden, que es para lo que están.
--   · V2  → employee_code y department en cardholder, y su secuencia.
--   · V3  → ledger de la concentradora (+ V3a corrige su fila de apertura).
--   · V4  → severidad, módulo y origen en la bitácora (+ V4a repara bases
--           creadas con la versión de este archivo que se quedó sin ellas).
--   · V5  → descripción y color propio en las categorías.
--   · V6  → una tarjeta activa de cada tipo por cuenta.
-- ============================================================

-- ── Limpieza para desarrollo (re-ejecutar). Descomenta si necesitas recrear.
--    OJO: borra datos. Respeta el orden inverso por las llaves foráneas.
-- DROP TABLE account_movement CASCADE CONSTRAINTS;
-- DROP TABLE concentrator_movement CASCADE CONSTRAINTS;
-- DROP TABLE card CASCADE CONSTRAINTS;
-- DROP TABLE account CASCADE CONSTRAINTS;
-- DROP TABLE concentrator_account CASCADE CONSTRAINTS;
-- DROP TABLE app_user CASCADE CONSTRAINTS;
-- DROP TABLE cardholder CASCADE CONSTRAINTS;
-- DROP TABLE category CASCADE CONSTRAINTS;
-- DROP TABLE audit_log CASCADE CONSTRAINTS;
-- DROP SEQUENCE seq_employee_code;

-- ============================================================
-- 1) category · catálogo global de propósitos (gestión de categorías = core)
-- ============================================================
--    color_index es el color con el que la categoría se pinta en TODA la app
--    (badge de la tabla de cuentas, pastel de la Vista Global, píldora del
--    detalle). Se guarda en vez de derivarse de la posición en el catálogo:
--    así lo elige quien crea la categoría, y dar de alta una nueva no repinta
--    las que ya existían. Los siete valores son los siete --sgfte-purpose-N de
--    la hoja de estilos, en el mismo orden que la paleta del modal (2041:155).
--
--    No se borran categorías: account.category_id es NOT NULL y apunta aquí,
--    así que una categoría en uso no se puede borrar sin arrastrar cuentas.
--    Retirarla es status = 'INACTIVE', que la saca de los desplegables y deja
--    intacto el histórico de las cuentas que la usaron.
CREATE TABLE category (
                          id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name    VARCHAR2(40) NOT NULL,
                          status      VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL,
                          description VARCHAR2(120),
                          color_index NUMBER(1) DEFAULT 1 NOT NULL,
                          CONSTRAINT uq_category_name   UNIQUE (name),
                          CONSTRAINT chk_category_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
                          CONSTRAINT chk_category_color  CHECK (color_index BETWEEN 1 AND 7)
);

-- ============================================================
-- 2) cardholder · Tarjetahabiente (empleado). El dinero NUNCA vive aquí.
--
--    employee_code es el código que se ve en pantalla ("DJE0077"): iniciales
--    del nombre completo + cuatro dígitos de seq_employee_code. Las iniciales
--    NO bastan para ser únicas —dos "Juan Pérez López" dan JPL—, así que la
--    unicidad la garantiza el número, no las letras. Se asigna una vez al dar
--    de alta y no se recalcula: corregir después una errata en el nombre no
--    debe cambiar un identificador ya emitido.
--
--    department es texto por ahora, con 'IT' como única opción. Cuando exista
--    un catálogo de áreas se convierte en FK y estos valores se migran.
-- ============================================================
CREATE TABLE cardholder (
                            id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            first_name    VARCHAR2(60)  NOT NULL,
                            last_name     VARCHAR2(60)  NOT NULL,
                            email         VARCHAR2(120) NOT NULL,
                            phone         VARCHAR2(20),
                            employee_code VARCHAR2(12)  NOT NULL,
                            department    VARCHAR2(60),
                            status        VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL,
                            created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                            CONSTRAINT uq_cardholder_email  UNIQUE (email),
                            CONSTRAINT uq_cardholder_employee_code UNIQUE (employee_code),
                            CONSTRAINT chk_cardholder_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- Parte numérica del código de empleado. Cuatro dígitos aguantan 9,999 altas
-- antes de tener que ensanchar la columna. NOCACHE para no perder tramos al
-- reiniciar la base; el volumen de altas no justifica el caché.
CREATE SEQUENCE seq_employee_code
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ============================================================
-- 3) concentrator_account · Cuenta Concentradora (fuente única de fondos).
--    Singleton: solo puede existir UNA fila (truco: columna 'singleton' única con CHECK).
-- ============================================================
CREATE TABLE concentrator_account (
                                      id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name       VARCHAR2(60) DEFAULT 'Cuenta Concentradora' NOT NULL,
                                      balance    NUMBER(16, 2) DEFAULT 0 NOT NULL,
                                      currency   CHAR(3) DEFAULT 'MXN' NOT NULL,
                                      singleton  CHAR(1) DEFAULT 'Y' NOT NULL,
                                      CONSTRAINT chk_concentrator_balance   CHECK (balance >= 0),
                                      CONSTRAINT chk_concentrator_currency  CHECK (currency = 'MXN'),
                                      CONSTRAINT chk_concentrator_singleton CHECK (singleton = 'Y'),
                                      CONSTRAINT uq_concentrator_singleton  UNIQUE (singleton)
);

-- ============================================================
-- 4) account · Cuenta con propósito. EL DINERO VIVE AQUÍ.
--    FK a cardholder (dueño) y a category (propósito).
--    Sin ON DELETE CASCADE a propósito: al borrar un cardholder, la lógica Java
--    debe reintegrar el saldo a la Concentradora ANTES de borrar (regla de negocio 4).
-- ============================================================
CREATE TABLE account (
                         id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         cardholder_id  NUMBER NOT NULL,
                         category_id    NUMBER NOT NULL,
                         account_number  VARCHAR2(20) NOT NULL,
                         balance        NUMBER(14, 2) DEFAULT 0 NOT NULL,
                         currency       CHAR(3) DEFAULT 'MXN' NOT NULL,
                         status         VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL,
                         created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                         CONSTRAINT fk_account_cardholder FOREIGN KEY (cardholder_id) REFERENCES cardholder(id),
                         CONSTRAINT fk_account_category   FOREIGN KEY (category_id)   REFERENCES category(id),
                         CONSTRAINT uq_account_number UNIQUE (account_number),
                         CONSTRAINT chk_account_balance   CHECK (balance >= 0),
                         CONSTRAINT chk_account_currency  CHECK (currency = 'MXN'),
                         CONSTRAINT chk_account_status    CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- ============================================================
-- 5) card · Tarjeta (punto de acceso a la cuenta). NO guarda dinero.
--    Borrar una tarjeta NO mueve dinero (regla de negocio 4).
-- ============================================================
CREATE TABLE card (
                      id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      account_id  NUMBER NOT NULL,
                      card_type   VARCHAR2(10) NOT NULL,
                      masked_pan  VARCHAR2(19),
                      status      VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL,
                      created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                      CONSTRAINT fk_card_account FOREIGN KEY (account_id) REFERENCES account(id),
                      CONSTRAINT chk_card_type   CHECK (card_type IN ('PHYSICAL', 'DIGITAL')),
                      CONSTRAINT chk_card_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'BLOCKED'))
);

-- Como mucho UNA tarjeta activa de cada tipo por cuenta: una física y una
-- digital. Índice único y no CHECK, porque un CHECK sólo ve la fila que se
-- inserta y aquí hay que mirar las hermanas.
--
-- El CASE lo limita a las ACTIVAS: en Oracle una entrada con todas sus columnas
-- en NULL no se indexa, así que las canceladas quedan fuera y reponer una
-- tarjeta perdida —invalidar y expedir otra— sigue siendo posible.
CREATE UNIQUE INDEX uq_card_active_type ON card (
    CASE WHEN status = 'ACTIVE' THEN account_id END,
    CASE WHEN status = 'ACTIVE' THEN card_type  END
);

-- ============================================================
-- 6) account_movement · Ledger inmutable de dinero (trazabilidad).
--    Cada depósito, retiro, transferencia P2P y reintegración deja registro.
-- ============================================================
CREATE TABLE account_movement (
                                  id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  account_id         NUMBER NOT NULL,
                                  movement_type      VARCHAR2(15) NOT NULL,
                                  amount             NUMBER(14, 2) NOT NULL,
                                  related_account_id NUMBER,          -- contraparte en transferencias P2P
                                  description        VARCHAR2(200),
                                  created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                                  CONSTRAINT fk_mov_account FOREIGN KEY (account_id)         REFERENCES account(id),
                                  CONSTRAINT fk_mov_related FOREIGN KEY (related_account_id) REFERENCES account(id),
                                  CONSTRAINT chk_mov_type   CHECK (movement_type IN
                                                                   ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER_IN', 'TRANSFER_OUT', 'REINTEGRATION')),
                                  CONSTRAINT chk_mov_amount CHECK (amount > 0)
);

-- Trigger: el ledger es inmutable (no se puede modificar ni borrar un movimiento).
CREATE OR REPLACE TRIGGER trg_account_movement_immutable
    BEFORE UPDATE OR DELETE ON account_movement
BEGIN
    RAISE_APPLICATION_ERROR(-20001,
                            'account_movement es inmutable: no se permite modificar ni borrar movimientos');
END;
/

-- ============================================================
-- 7) concentrator_movement · Ledger inmutable de la Concentradora.
--
--    concentrator_account es UNA fila con saldo mutable y sin historia. Las
--    dispersiones y reintegraciones dejaban rastro del lado de la cuenta, en
--    account_movement, pero FONDEAR la concentradora no dejaba rastro en ningún
--    sitio: era la única operación del sistema que movía dinero sin registro.
--
--    Sirve para dos cosas: auditar quién mete dinero, y responder "cuánto había
--    hace un periodo" en Analíticas.
--
--    balance_after se guarda explícitamente en vez de recalcularse sumando: el
--    saldo histórico se lee de una fila y no depende de que la suma de todos
--    los movimientos anteriores cuadre.
-- ============================================================
CREATE TABLE concentrator_movement (
                                       id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       movement_type VARCHAR2(15)  NOT NULL,
                                       amount        NUMBER(16, 2) NOT NULL,
                                       balance_after NUMBER(16, 2) NOT NULL,
                                       actor         VARCHAR2(120),   -- quién fondeó; NULL cuando lo mueve el sistema
                                       created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                                       CONSTRAINT chk_conc_mov_type CHECK (movement_type IN
                                                                           ('FUNDING', 'DISPERSION', 'REINTEGRATION')),
                                       CONSTRAINT chk_conc_mov_amount  CHECK (amount > 0),
                                       CONSTRAINT chk_conc_mov_balance CHECK (balance_after >= 0)
);

CREATE INDEX idx_conc_mov_created ON concentrator_movement (created_at);

-- El ledger es inmutable, igual que account_movement.
CREATE OR REPLACE TRIGGER trg_concentrator_movement_immutable
    BEFORE UPDATE OR DELETE ON concentrator_movement
BEGIN
    RAISE_APPLICATION_ERROR(-20003,
                            'concentrator_movement es inmutable: no se permite modificar ni borrar movimientos');
END;
/

-- ============================================================
-- 8) app_user · Usuarios que inician sesión (login). Rol: ADMIN | TARJETAHABIENTE.
--    Guarda SOLO el hash bcrypt de la contraseña, nunca texto plano.
--    cardholder_id enlaza el login de un TARJETAHABIENTE con su ficha; NULL en admins.
-- ============================================================
CREATE TABLE app_user (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR2(120) NOT NULL,
    password_hash VARCHAR2(72)  NOT NULL,
    full_name     VARCHAR2(120) NOT NULL,
    role          VARCHAR2(20)  DEFAULT 'ADMIN' NOT NULL,
    cardholder_id NUMBER,
    status        VARCHAR2(10)  DEFAULT 'ACTIVE' NOT NULL,
    created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_app_user_email      UNIQUE (email),
    CONSTRAINT chk_app_user_role      CHECK (role IN ('ADMIN', 'TARJETAHABIENTE')),
    CONSTRAINT chk_app_user_status    CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT fk_app_user_cardholder FOREIGN KEY (cardholder_id) REFERENCES cardholder (id)
);

-- 9) Microservicio de Auditoría: bitácora inmutable de eventos del sistema.
--
--    La pantalla "Logs y Auditoría" (Figma 253:43) muestra seis columnas
--    —fecha, NIVEL, acción, usuario, MÓDULO, ORIGEN—, de ahí las tres últimas.
--
--    `severity` y no `level` a propósito: LEVEL es una pseudocolumna de Oracle
--    (la de CONNECT BY) y usarla como nombre obliga a entrecomillar en cada
--    consulta.
--
--    ip_address llega a 45 caracteres para que quepa una IPv6 completa; el
--    contenedor y el proxy pueden entregar ::1 o una dirección mapeada.
--
--    Van DESPUÉS de created_at, aunque leído así quede raro, porque es donde
--    las deja el ALTER de V4: una base creada desde este archivo y otra migrada
--    quedan idénticas, columna por columna. Que diverjan es justo lo que
--    produce un "en mi máquina sí funciona".
CREATE TABLE audit_log (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type  VARCHAR2(40)  NOT NULL,   -- LOGIN, DEPOSIT, TRANSFER, DELETE, NOTIFICATION, ...
    detail      VARCHAR2(400),
    actor       VARCHAR2(120),            -- quién lo hizo (email admin, sistema, etc.)
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    severity    VARCHAR2(10) DEFAULT 'INFO' NOT NULL,
    module      VARCHAR2(30),
    ip_address  VARCHAR2(45),
    CONSTRAINT chk_audit_severity CHECK (severity IN ('INFO', 'ALERTA', 'CRIT'))
);

-- Se consulta casi siempre por fecha descendente y filtrando por severidad.
CREATE INDEX idx_audit_created  ON audit_log (created_at);
CREATE INDEX idx_audit_severity ON audit_log (severity);

-- El log es inmutable, igual que account_movement.
CREATE OR REPLACE TRIGGER trg_audit_log_immutable
BEFORE UPDATE OR DELETE ON audit_log
BEGIN
    RAISE_APPLICATION_ERROR(-20002, 'audit_log es inmutable: no se puede modificar ni borrar');
END;
/

-- ============================================================
-- Notas de reglas de negocio que se aplican en la CAPA JAVA (no en SQL):
--   · Reintegración automática: al borrar account/cardholder, el saldo regresa
--     a concentrator_account antes de borrar; las tarjetas se invalidan.
--   · Transferencia P2P: solo entre cuentas con el MISMO category_id (mismo propósito).
--   · Toda operación de dinero es transaccional y escribe en account_movement.
--   · Todo cambio de saldo de la Concentradora escribe en concentrator_movement.
--     El asiento se escribe dentro de ConcentratorDao, junto a los tres métodos
--     que tocan el saldo, para que ninguna ruta pueda moverlo sin dejar rastro.
--   · El código de empleado se genera al dar de alta (ver EmployeeCode) y no se
--     vuelve a calcular al leer.
-- ============================================================

-- ============================================================
-- Seed mínimo para poder trabajar
-- ============================================================
INSERT INTO concentrator_account (name, balance) VALUES ('Cuenta Concentradora', 1000000.00);

-- Los códigos consumen la secuencia en vez de ir escritos a mano: si se fijaran
-- como 'JL0001', la secuencia volvería a entregar el 1 en la primera alta y
-- chocaría contra uq_cardholder_employee_code.
INSERT INTO cardholder (first_name, last_name, email, phone, employee_code, department)
VALUES ('Juan', 'Lopez', 'juanlopez@empresa.com', '7771234567',
        'JL' || LPAD(seq_employee_code.NEXTVAL, 4, '0'), 'IT');
INSERT INTO cardholder (first_name, last_name, email, phone, employee_code, department)
VALUES ('Raul', 'Torres', 'raultorres@empresa.com', '7773216548',
        'RT' || LPAD(seq_employee_code.NEXTVAL, 4, '0'), 'IT');

INSERT INTO category (name, color_index, description) VALUES ('Gasolina',  1, 'Combustible vehicular asignado');
INSERT INTO category (name, color_index, description) VALUES ('Viajes',    2, 'Viáticos y viajes corporativos');
INSERT INTO category (name, color_index, description) VALUES ('Alimentos', 3, 'Alimentos y restaurantes');

-- Admin inicial. Password: sgfte
INSERT INTO app_user (email, password_hash, full_name, role) VALUES ('admin@empresa.com', '$2a$12$EtVTq2PPQ8dp/XE0GHMomeJKZuU6bT.KRpGK91l3ji6rm5mBHFjFi', 'Administrador General', 'ADMIN');

-- Fila de apertura del ledger de la Concentradora.
--
-- Va FECHADA EN EL PASADO, no con SYSTIMESTAMP, y eso es lo importante: el saldo
-- "de hace un periodo" se busca como el último movimiento ANTERIOR al inicio de
-- la ventana. Una apertura fechada hoy no es anterior a ninguna ventana, así que
-- la comparación de Analíticas saldría en guion para siempre. 400 días cubren de
-- sobra la ventana más larga del selector (12 meses).
INSERT INTO concentrator_movement (movement_type, amount, balance_after, actor, created_at)
SELECT 'FUNDING', GREATEST(balance, 0.01), balance, 'saldo inicial', SYSDATE - 400
  FROM concentrator_account
 WHERE singleton = 'Y';

COMMIT;
