-- ============================================================
-- V10 · Catálogo de departamentos
--
-- Hasta aquí el departamento de un empleado era texto libre en
-- cardholder.department, y el desplegable del alta ofrecía una sola opción
-- escrita a mano en el JSP ("IT"). Eso significaba que:
--
--   · dos formas de escribir lo mismo ("IT" e "it") eran dos departamentos
--     distintos para el filtro de la pantalla de empleados;
--   · no había forma de dar de alta uno nuevo sin tocar código;
--   · y renombrarlo obligaba a un UPDATE masivo sobre cardholder.
--
-- Se convierte en catálogo, igual que category: una tabla propia y una FK.
-- Misma forma que category a propósito —nombre único, descripción opcional,
-- baja lógica por status— porque es el mismo tipo de cosa: un catálogo que
-- alimenta un desplegable y que no se borra, se retira.
--
-- Lo que NO lleva y category sí: color_index. El color de una categoría
-- distingue propósitos en tablas y gráficas; un departamento no se pinta en
-- ninguna parte.
--
-- Aplicar sobre una base ya creada. En una base nueva esto ya viene en
-- schema.sql / init-schema.sql.
-- ============================================================

CREATE TABLE department (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(60)  NOT NULL,
    description VARCHAR2(120),
    status      VARCHAR2(10)  DEFAULT 'ACTIVE' NOT NULL,
    created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_department_name    UNIQUE (name),
    CONSTRAINT chk_department_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- 1) El catálogo nace con lo que ya existía en los datos, sin inventar nada:
--    cada valor distinto de cardholder.department se vuelve una fila.
INSERT INTO department (name)
SELECT DISTINCT TRIM(department)
  FROM cardholder
 WHERE department IS NOT NULL
   AND TRIM(department) IS NOT NULL;

-- 2) Y los que la empresa va a usar de verdad, si no estaban ya.
INSERT INTO department (name, description)
SELECT 'IT', 'Tecnologías de la información' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM department WHERE name = 'IT');
INSERT INTO department (name, description)
SELECT 'Finanzas', 'Contabilidad y control de gastos' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM department WHERE name = 'Finanzas');
INSERT INTO department (name, description)
SELECT 'Operaciones', 'Logística y operación diaria' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM department WHERE name = 'Operaciones');
INSERT INTO department (name, description)
SELECT 'Ventas', 'Fuerza comercial y viáticos' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM department WHERE name = 'Ventas');
INSERT INTO department (name, description)
SELECT 'Recursos Humanos', 'Personal y prestaciones' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM department WHERE name = 'Recursos Humanos');

-- 3) La columna nueva, poblada desde el texto que ya había. Se hace en este
--    orden —crear, llenar, y sólo entonces borrar la vieja— para que ninguna
--    fila pierda su departamento por el camino.
ALTER TABLE cardholder ADD (department_id NUMBER);

UPDATE cardholder ch
   SET ch.department_id = (SELECT d.id FROM department d
                            WHERE d.name = TRIM(ch.department))
 WHERE ch.department IS NOT NULL;

ALTER TABLE cardholder ADD CONSTRAINT fk_cardholder_department
    FOREIGN KEY (department_id) REFERENCES department (id);

-- Sin ON DELETE: un departamento no se borra nunca, se retira (status). Si
-- alguien intenta un DELETE con empleados dentro, la FK lo impide, que es
-- exactamente lo que debe pasar.

ALTER TABLE cardholder DROP COLUMN department;

CREATE INDEX idx_cardholder_department ON cardholder (department_id);
