-- ============================================================
-- V12 · funding_deposit · el dinero entra con referencia bancaria, o no entra.
--
-- Hasta aquí fondear era esto: un administrador tecleaba un monto y el saldo
-- de la Concentradora subía. El método ("SPEI", "Efectivo") ni siquiera se
-- guardaba en el ledger — se metía en el texto de la bitácora y se perdía. En
-- términos de PLD eso es la etapa de COLOCACIÓN sin ningún control: dinero que
-- aparece de la nada, sin origen, sin contraparte y sin nada que un banco
-- pueda confirmar.
--
-- El ledger ya era inmutable, pero la inmutabilidad de un asiento inventado
-- sólo garantiza que la mentira no se puede borrar. Faltaba la PROCEDENCIA.
--
-- A partir de aquí la Concentradora tiene CLABE y el saldo sólo sube cuando se
-- registra un depósito que trae una referencia verificable fuera del sistema.
-- El administrador deja de CREAR dinero y pasa a CONCILIAR el que el banco
-- reporta.
--
-- ── Los dos canales ─────────────────────────────────────────
--
-- SPEI        · la transferencia trae clave de rastreo y cuenta ordenante. Es
--               el canal con trazabilidad completa: la clave de rastreo se
--               puede cotejar contra el CEP que publica Banxico.
-- VENTANILLA  · depósito en efectivo en sucursal. NO existe cuenta ordenante
--               —nadie transfirió desde ninguna cuenta— y no hay clave de
--               rastreo; lo que hay es el folio de la ficha de depósito.
--
-- Ojo con la diferencia respecto al viejo "Efectivo" del modal: aquello era
-- "apareció dinero y alguien escribió una palabra". Esto es un depósito que el
-- banco recibió, con folio, sucursal, fecha y depositante identificado. No es
-- el mismo hecho.
--
-- La regla de diseño, y es la que hay que poder defender: EL CANAL CON MENOS
-- TRAZABILIDAD CARGA CON MÁS IDENTIFICACIÓN. Un SPEI se identifica solo, por
-- la cuenta que lo ordenó, así que el RFC es opcional. Un depósito en efectivo
-- no tiene cuenta que lo identifique, así que el RFC del depositante es
-- OBLIGATORIO. Las dos reglas viven en CHECK constraints, no en un if de Java:
-- la base sabe que un SPEI tiene que traer cuenta ordenante y que un depósito
-- en ventanilla no puede traerla.
--
-- ── Lo que NO se guarda aquí ────────────────────────────────
--
-- Sólo se guardan los depósitos APLICADOS. Un intento rechazado —CLABE
-- inválida, referencia repetida, beneficiario que no somos nosotros— no deja
-- fila: deja un ALERTA en la bitácora, que es donde ya viven los intentos
-- fallidos (ver DISPERSION_REJECTED). Así `referencia` UNIQUE significa
-- exactamente "dinero que entró" y no hay que interpretar estados.
--
-- Aplicar sobre una base ya creada. En una base nueva ya viene en schema.sql /
-- init-schema.sql.
-- ============================================================

-- ── 1) La Concentradora tiene una CLABE: es el destino al que se transfiere.
ALTER TABLE concentrator_account ADD (clabe CHAR(18));

UPDATE concentrator_account
   SET clabe = '012180000000000002'
 WHERE singleton = 'Y' AND clabe IS NULL;

COMMENT ON COLUMN concentrator_account.clabe IS
    'CLABE de 18 dígitos de la cuenta concentradora. Destino de todo fondeo.';

-- ── 2) El depósito: un hecho externo con referencia bancaria.
--
--     `referencia` es lo que emitió el banco: en SPEI la clave de rastreo, en
--     ventanilla el folio de la ficha de depósito. Va UNIQUE, y es la
--     restricción más importante del archivo: hace que contabilizar dos veces
--     el mismo depósito sea IMPOSIBLE, no "desaconsejable". La regla vive en el
--     esquema y no en la disciplina de quien captura, igual que la
--     inmutabilidad del ledger.
--
--     La razón social es obligatoria en los dos canales: un depósito sin
--     depositante identificado no se registra. El RFC sólo lo es en ventanilla,
--     por la regla de arriba — el SPEI ya se identifica por su cuenta ordenante.
--
--     fecha_operacion es cuándo lo hizo el banco; recibido_en, cuándo lo supimos
--     nosotros. No son lo mismo y conviene poder compararlas.
--
--     OJO al escribir aquí: en SQL*Plus una línea EN BLANCO dentro de una
--     sentencia la da por terminada, y el script se aplica a medias sin decir
--     nada. Por eso este CREATE TABLE va compacto, como los demás del esquema.
CREATE TABLE funding_deposit (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canal               VARCHAR2(12)  NOT NULL,   -- SPEI | VENTANILLA
    referencia          VARCHAR2(40)  NOT NULL,   -- clave de rastreo o folio de ficha
    ordenante_nombre    VARCHAR2(160) NOT NULL,   -- razón social de quien depositó
    ordenante_rfc       VARCHAR2(13),             -- obligatorio en ventanilla
    ordenante_clabe     CHAR(18),                 -- sólo SPEI: no existe en efectivo
    institucion         VARCHAR2(60)  NOT NULL,
    sucursal            VARCHAR2(60),             -- sólo ventanilla
    beneficiario_clabe  CHAR(18)      NOT NULL,   -- tiene que ser la nuestra
    monto               NUMBER(16, 2) NOT NULL,
    concepto            VARCHAR2(40),
    referencia_numerica NUMBER(7),                -- referencia numérica del SPEI
    fecha_operacion     TIMESTAMP     NOT NULL,
    recibido_en         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_funding_deposit_ref UNIQUE (referencia),
    CONSTRAINT chk_funding_canal CHECK (canal IN ('SPEI', 'VENTANILLA')),
    CONSTRAINT chk_funding_monto CHECK (monto > 0),
    -- Un SPEI SIEMPRE viene de una cuenta; un depósito en efectivo NUNCA.
    CONSTRAINT chk_funding_ordenante_clabe CHECK (
        (canal = 'SPEI'       AND ordenante_clabe IS NOT NULL) OR
        (canal = 'VENTANILLA' AND ordenante_clabe IS NULL)),
    -- El canal sin cuenta ordenante compensa identificando al depositante.
    CONSTRAINT chk_funding_ventanilla_rfc CHECK (
        canal <> 'VENTANILLA' OR ordenante_rfc IS NOT NULL),
    -- La sucursal sólo tiene sentido donde alguien se paró en un mostrador.
    CONSTRAINT chk_funding_sucursal CHECK (
        canal = 'VENTANILLA' OR sucursal IS NULL)
);

CREATE INDEX idx_funding_deposit_fecha ON funding_deposit (fecha_operacion);

-- Un depósito tampoco se corrige ni se borra: es el respaldo de un asiento del
-- ledger, y el ledger ya es inmutable. Si el respaldo se pudiera editar, la
-- inmutabilidad del asiento no valdría nada.
CREATE OR REPLACE TRIGGER trg_funding_deposit_immutable
    BEFORE UPDATE OR DELETE ON funding_deposit
BEGIN
    RAISE_APPLICATION_ERROR(-20004,
        'funding_deposit es inmutable: un depósito registrado no se modifica ni se borra');
END;
/

-- ── 3) El enlace: cada FUNDING del ledger apunta a su depósito.
--
--     Ésta es la cadena completa de trazabilidad, y es la que se enseña en la
--     defensa: peso → asiento del ledger → depósito → clave de rastreo → CEP
--     verificable en Banxico.
--
--     Sólo un FUNDING puede traer depósito: una dispersión o una reintegración
--     son movimientos internos y no tienen nada que respaldar del lado de
--     afuera.
--
--     Nullable a propósito, y no NOT NULL para los FUNDING: el asiento de
--     apertura que siembra el esquema —el saldo inicial, fechado 400 días
--     atrás— es anterior a todo esto y no tiene depósito que enseñar. Se queda
--     así, sin rellenar con un SPEI inventado: marca justo dónde empieza la
--     trazabilidad, y eso es más honesto que fabricarle un respaldo.
ALTER TABLE concentrator_movement ADD (funding_deposit_id NUMBER);

ALTER TABLE concentrator_movement ADD CONSTRAINT fk_conc_mov_deposit
    FOREIGN KEY (funding_deposit_id) REFERENCES funding_deposit (id);

ALTER TABLE concentrator_movement ADD CONSTRAINT chk_conc_mov_deposit_only_funding
    CHECK (funding_deposit_id IS NULL OR movement_type = 'FUNDING');

-- ── 4) La vista global aprende a enseñar la referencia.
--
--     /admin/movimientos es donde se mira el ledger, así que es donde tiene
--     que verse de dónde vino cada fondeo. Sin esto la trazabilidad existiría
--     en la base pero no en la pantalla, que es donde se defiende.
CREATE OR REPLACE VIEW v_movement AS
SELECT 'CUENTA'                             AS scope,
       m.id                                 AS source_id,
       m.movement_type                      AS movement_type,
       m.amount                             AS amount,
       CASE WHEN m.movement_type IN ('DEPOSIT', 'TRANSFER_IN')
            THEN 'IN' ELSE 'OUT' END        AS direction,
       m.description                        AS description,
       a.id                                 AS account_id,
       a.account_number                     AS account_number,
       ch.first_name || ' ' || ch.last_name AS holder,
       ch.employee_code                     AS employee_code,
       cat.id                               AS category_id,
       cat.name                             AS category_name,
       cat.color_index                      AS color_index,
       r.account_number                     AS related_number,
       CAST(NULL AS VARCHAR2(120))          AS actor,
       CAST(NULL AS NUMBER(16, 2))          AS balance_after,
       CAST(NULL AS VARCHAR2(12))           AS canal,
       CAST(NULL AS VARCHAR2(40))           AS referencia,
       CAST(NULL AS VARCHAR2(160))          AS ordenante,
       m.created_at                         AS created_at
  FROM account_movement m
  JOIN account    a   ON a.id   = m.account_id
  JOIN cardholder ch  ON ch.id  = a.cardholder_id
  JOIN category   cat ON cat.id = a.category_id
  LEFT JOIN account r ON r.id   = m.related_account_id
UNION ALL
SELECT 'CONCENTRADORA',
       cm.id,
       cm.movement_type,
       cm.amount,
       CASE WHEN cm.movement_type IN ('FUNDING', 'REINTEGRATION')
            THEN 'IN' ELSE 'OUT' END,
       CAST(NULL AS VARCHAR2(200)),
       CAST(NULL AS NUMBER),
       CAST(NULL AS VARCHAR2(20)),
       CAST(NULL AS VARCHAR2(121)),
       CAST(NULL AS VARCHAR2(12)),
       CAST(NULL AS NUMBER),
       CAST(NULL AS VARCHAR2(40)),
       CAST(NULL AS NUMBER),
       CAST(NULL AS VARCHAR2(20)),
       cm.actor,
       cm.balance_after,
       fd.canal,
       fd.referencia,
       fd.ordenante_nombre,
       cm.created_at
  FROM concentrator_movement cm
  LEFT JOIN funding_deposit fd ON fd.id = cm.funding_deposit_id;
