-- SGFTE · Vertical slice: Alta de Tarjetahabiente (Cardholder)
-- Oracle 21c XE. Run this connected to your app schema (e.g. user SGFTE on XEPDB1).

CREATE TABLE cardholder (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR2(60)  NOT NULL,
    last_name   VARCHAR2(60)  NOT NULL,
    email       VARCHAR2(120) NOT NULL,
    phone       VARCHAR2(20),
    status      VARCHAR2(10)  DEFAULT 'ACTIVE' NOT NULL,
    created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_cardholder_email UNIQUE (email),
    CONSTRAINT chk_cardholder_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- Quick check after inserting from the app:
-- SELECT id, first_name, last_name, email, status, created_at FROM cardholder ORDER BY id;
