-- SGFTE · V3 · Ledger de la Cuenta Concentradora
-- Oracle 23. Ejecutar conectado al esquema SGFTE.
--
-- Por qué: concentrator_account es UNA fila con un saldo mutable y sin
-- historia. Las dispersiones y las reintegraciones dejaban rastro en
-- account_movement (del lado de la cuenta), pero FONDEAR la concentradora no
-- dejaba rastro en ningún sitio: ni ledger, ni audit_log. Es decir, meter
-- dinero a la empresa era la única operación del sistema sin registro.
--
-- Con esta tabla:
--   · Analíticas puede comparar el saldo contra el de hace un mes.
--   · Y, más importante, queda constancia de quién fondeó, cuánto y cuándo.
--
-- balance_after se guarda explícitamente en vez de recalcularse sumando: así
-- el saldo histórico se lee de una fila y no depende de que la suma de todos
-- los movimientos anteriores cuadre.

CREATE TABLE concentrator_movement (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_type VARCHAR2(15)  NOT NULL,
    amount        NUMBER(16, 2) NOT NULL,
    balance_after NUMBER(16, 2) NOT NULL,
    actor         VARCHAR2(120),
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_conc_mov_type CHECK (movement_type IN
                                        ('FUNDING', 'DISPERSION', 'REINTEGRATION')),
    CONSTRAINT chk_conc_mov_amount  CHECK (amount > 0),
    CONSTRAINT chk_conc_mov_balance CHECK (balance_after >= 0)
);

CREATE INDEX idx_conc_mov_created ON concentrator_movement (created_at);

-- El ledger es inmutable, igual que account_movement.
CREATE OR REPLACE TRIGGER trg_concentrator_movement_immutable
    BEFORE UPDATE OR DELETE ON concentrator_movement
BEGIN
    RAISE_APPLICATION_ERROR(-20002,
        'concentrator_movement es inmutable: no se permite modificar ni borrar movimientos');
END;
/

-- ---------------------------------------------------------------------------
-- Fila de apertura: fija el saldo de hoy como punto de partida.
--
-- Sin ella, la primera comparación "vs periodo anterior" no tendría contra qué
-- medir y saldría como si la concentradora hubiera arrancado en cero.
-- ---------------------------------------------------------------------------
INSERT INTO concentrator_movement (movement_type, amount, balance_after, actor)
SELECT 'FUNDING', GREATEST(balance, 0.01), balance, 'migración V3'
  FROM concentrator_account
 WHERE singleton = 'Y';

COMMIT;

-- Comprobación:
-- SELECT movement_type, amount, balance_after, actor, created_at
--   FROM concentrator_movement ORDER BY id;
