-- SGFTE · V8 · Bitácora de notificaciones del tarjetahabiente
-- Oracle 23. Ejecutar conectado al esquema SGFTE.
--
-- Por qué: la pantalla "Notificaciones" del tarjetahabiente necesita "todo lo
-- que se le ha avisado por correo", scopeado a ÉL. audit_log no sirve para
-- eso: guarda quién HIZO la acción (actor), no a quién iba dirigida, y el
-- destinatario del aviso de dinero recibido vive enterrado en el texto de
-- detail ("asunto -> correo@empresa.com"). Buscar por ahí es un LIKE sobre
-- toda la bitácora del sistema, no una columna.
--
-- event_type reutiliza el mismo vocabulario de AuditEvent que ya usa
-- audit_log — así el título de cada fila ("Nueva tarjeta asignada"...) sale
-- del mismo enum en los dos lados y no hay dos catálogos de texto que puedan
-- desalinearse. category se guarda materializada (SEGURIDAD / ADMINISTRATIVA,
-- derivada del módulo del evento) por la misma razón que audit_log guarda
-- severity y module aparte del event_type: es la columna por la que se filtra
-- todo el tiempo, y calcularla en cada lectura sólo para poder indexarla no
-- tendría sentido.
--
-- Inmutable, igual que audit_log y account_movement: es un registro de lo que
-- se avisó, no un estado que se edite.
CREATE TABLE notification (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cardholder_id NUMBER NOT NULL,
    event_type    VARCHAR2(40) NOT NULL,
    category      VARCHAR2(20) NOT NULL,
    detail        VARCHAR2(400),
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_notification_cardholder FOREIGN KEY (cardholder_id) REFERENCES cardholder(id),
    CONSTRAINT chk_notification_category CHECK (category IN ('SEGURIDAD', 'ADMINISTRATIVA'))
);

-- Se consulta casi siempre "las de este cardholder, más recientes primero" y
-- filtrando por categoría, igual que audit_log.
CREATE INDEX idx_notification_cardholder ON notification (cardholder_id, created_at);
CREATE INDEX idx_notification_category   ON notification (category);

CREATE OR REPLACE TRIGGER trg_notification_immutable
    BEFORE UPDATE OR DELETE ON notification
BEGIN
    RAISE_APPLICATION_ERROR(-20004, 'notification es inmutable: no se permite modificar ni borrar');
END;
/

COMMIT;

-- Comprobación:
-- SELECT n.id, ch.email, n.event_type, n.category, n.created_at
--   FROM notification n JOIN cardholder ch ON ch.id = n.cardholder_id
--  ORDER BY n.created_at DESC FETCH FIRST 20 ROWS ONLY;
